
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int operador_and = 28;
  public static final int palabra_devolver = 16;
  public static final int operador_relacional = 27;
  public static final int tipo_cadena = 10;
  public static final int palabra_funcion = 8;
  public static final int tipo_booleano = 12;
  public static final int coma = 35;
  public static final int operador_multiplicacion = 20;
  public static final int igual = 17;
  public static final int identificador = 5;
  public static final int fin_programa = 3;
  public static final int operador_suma = 18;
  public static final int llave_cierre = 7;
  public static final int operador_mayor_igual = 33;
  public static final int tipo_decimal = 11;
  public static final int llave_apertura = 6;
  public static final int palabra_clase = 4;
  public static final int numero = 22;
  public static final int operador_menor_igual = 32;
  public static final int palabra_sino = 26;
  public static final int operador_division = 21;
  public static final int operador_resta = 19;
  public static final int EOF = 0;
  public static final int punto_coma = 15;
  public static final int operador_or = 29;
  public static final int parentesis_apertura = 13;
  public static final int error = 1;
  public static final int operador_igual = 34;
  public static final int tipo_entero = 9;
  public static final int palabra_sino_si = 25;
  public static final int parentesis_cierre = 14;
  public static final int palabra_si = 24;
  public static final int inicio_programa = 2;
  public static final int operador_menor = 30;
  public static final int operador_mayor = 31;
  public static final int cadena = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "inicio_programa",
  "fin_programa",
  "palabra_clase",
  "identificador",
  "llave_apertura",
  "llave_cierre",
  "palabra_funcion",
  "tipo_entero",
  "tipo_cadena",
  "tipo_decimal",
  "tipo_booleano",
  "parentesis_apertura",
  "parentesis_cierre",
  "punto_coma",
  "palabra_devolver",
  "igual",
  "operador_suma",
  "operador_resta",
  "operador_multiplicacion",
  "operador_division",
  "numero",
  "cadena",
  "palabra_si",
  "palabra_sino_si",
  "palabra_sino",
  "operador_relacional",
  "operador_and",
  "operador_or",
  "operador_menor",
  "operador_mayor",
  "operador_menor_igual",
  "operador_mayor_igual",
  "operador_igual",
  "coma"
  };
}

